apiVersion: v1
kind: Secret
metadata:
    name: pocket-id
    namespace: pocket-id
type: Opaque
stringData:
    encryption-key: ENC[AES256_GCM,data:td9z/5kdMCGEqlhq0OCtayqx3ve4hs/08+eUxltZoErEFg6lR0R2q/K/B3I=,iv:G333hlRTh4UeIb+yS+4d+I079gcrCOWqoerY29jdr+c=,tag:DQVYZyGzqJkhi5lvASFX8g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNVjVMcW9iQkhLNGtscXdI
            WkdrWnA2Q1NwM25zVlVRMDBhbHVsZHA3OWpJCkt5K1pSVnRFMjdOMDFUZGRnTG5I
            MEFJNmNTRXgzYk5Sb1VHcVRWSGFIcGMKLS0tIDdRVE1FQjIrOWdrR1huZHc1SVVx
            MW03aHVYVWtaWDVWd0xKMWxEeC9pQVkK75PJkEBEw/iD+ZSwy599M6pB41osYDbl
            1PHjtdNSnl33BGp1BWVRHRex/nU5TqHeCS/oLx3zLLc6cOnydwKumA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age194e8gmr9ctdzp2h3jzfel03xgx9e9rses3cncskr2r5qnpykyadqzuva8c
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-13T14:34:34Z"
    mac: ENC[AES256_GCM,data:h9mF2YUs8oVX+i3FiMDP8ZIAmKmO/HIwn/kiLTulAsFhqG0zw5V1Eq5bIU9wesoThNxqefsF5ZvT+5m6g5wvZpYxFaFK2ITUBsKq6M4ss2G7Wd2Z5dmWBqESopu9xJGIjIjqrue+MYLX69Lp4GDYpiaaivNmbhrMxA8334Tmnv0=,iv:izuz6eUIa9gHJZZ4saSNlNaJz7cgKOJ2n/NNbiV1Lcg=,tag:3lfz8xc8+4a7VTuvFAFdmg==,type:str]
    version: 3.13.3
