apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy
    namespace: home-assistant
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:j5552VALTsx3DfCQQvzYpCzEc2aPnDNPMNAzVdgLWGtErd1S,iv:+deaoyQq1Zqh1dJFlqThQY0hBuaD123gDHZEVBn9wuc=,tag:C+pGwDIBzm3pEaVFvnkC3A==,type:str]
    client-secret: ENC[AES256_GCM,data:zdTupzhAtUpDjjKGnCF4080pzTFaX6JLH73RxUSyEao=,iv:/MCRCCbC+J89/ZOCkEKDiAR5ajVo09iK8nAjOU0DtaI=,tag:hDNDVHmhUoKSXG+CDVuFIQ==,type:str]
    cookie-secret: ENC[AES256_GCM,data:PBtPV5dqBqv0pYLsMTqKajB3jQ8lGcj94sXpawk4LoqlMAzoefgRtDXeA1M=,iv:05+tgwZCgTFNVrEG4adUJqKfWGUJ+ReCxIPUNlBFsSQ=,tag:g/IiGzcyHOFJ1ZPMMbA6bA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoTGtrNCswTjlCZDFLUWJN
            c0FVYnkyNkh3YTYxZmdEQ3NUdkk2QmgxOERVCmJBVzVKOXQ2UmxwRG1SQ1dsc2Yx
            WUt4Mlg3YUZ1TnlGTGQ5WnJ5Y0ZoSk0KLS0tIEJaUldodi9UMkd0TkhQUFFoVUh4
            TmpWVXFpdjJFcVhLY2NTNk44aXVRT1UKCPYMMMezIJIhB4MOtywCU2QfX/qht/7D
            Pm0MAhNLON+9p0FMYVDxO3KXjG64XEf2CLdKCTD7OkQ13VMOwxrMvw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age194e8gmr9ctdzp2h3jzfel03xgx9e9rses3cncskr2r5qnpykyadqzuva8c
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-13T16:30:28Z"
    mac: ENC[AES256_GCM,data:y2RFovmvm/B8xGUxgvRwEVqh65TzhZ3F8yu8EcMLAKlGAQfdJE6vKUpmHtBCES77UNfD9WQNP+7q18pDFXBNHKXmTzctEWFJF/SHiqTsS/lKQtH32hC6dTtOugN4QX9jOCt1JrQgFKAmfGTShRK0Z7jJ54GAEdFNeo0RbXKRAv4=,iv:YOBLWS9/uPnmVXD1SsBlDhehjfpycfRnpCAmFlkSKPo=,tag:NfPnu814+M+V9fdYTvAeJg==,type:str]
    version: 3.13.3
