apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy
    namespace: home-assistant
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:j5552VALTsx3DfCQQvzYpCzEc2aPnDNPMNAzVdgLWGtErd1S,iv:+deaoyQq1Zqh1dJFlqThQY0hBuaD123gDHZEVBn9wuc=,tag:C+pGwDIBzm3pEaVFvnkC3A==,type:str]
    client-secret: ENC[AES256_GCM,data:zdTupzhAtUpDjjKGnCF4080pzTFaX6JLH73RxUSyEao=,iv:/MCRCCbC+J89/ZOCkEKDiAR5ajVo09iK8nAjOU0DtaI=,tag:hDNDVHmhUoKSXG+CDVuFIQ==,type:str]
    cookie-secret: ENC[AES256_GCM,data:3rrpUOv6aMGaIIb4C00/HA0knwlWJs8883IzjAVVDEA=,iv:E1o4q6QZwHumBisj8Te6jndmoWdL28StfUvFiye3U8M=,tag:yvgaMpc5QZa3plgHkUbDqg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoTGtrNCswTjlCZDFLUWJN
            c0FVYnkyNkh3YTYxZmdEQ3NUdkk2QmgxOERVCmJBVzVKOXQ2UmxwRG1SQ1dsc2Yx
            WUt4Mlg3YUZ1TnlGTGQ5WnJ5Y0ZoSk0KLS0tIEJaUldodi9UMkd0TkhQUFFoVUh4
            TmpWVXFpdjJFcVhLY2NTNk44aXVRT1UKCPYMMMezIJIhB4MOtywCU2QfX/qht/7D
            Pm0MAhNLON+9p0FMYVDxO3KXjG64XEf2CLdKCTD7OkQ13VMOwxrMvw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age194e8gmr9ctdzp2h3jzfel03xgx9e9rses3cncskr2r5qnpykyadqzuva8c
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-13T16:54:16Z"
    mac: ENC[AES256_GCM,data:Wtn0FYtDP5Tjl1sN+jszpGZtroE+3bYolSuozaWnLvXejTj+LiJtMN330vNxGb01fSb7XQ/oyumt5j/ja4ef75SJR0C+abDTxolfwskSoEVX5LeOsUVQ7Hk90b+L94NpbdgKRjHSTxp4RenEXa4lVzkNzWCUILWtx7AzISGVGqc=,iv:ln822mQfcSW6TMQvWTbjIQi0hBrFn1T2qbZIF/kDbRA=,tag:uqo7miFlAsUvzwsDb5btIQ==,type:str]
    version: 3.13.3
